spring:
  datasource:
    url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  activiti:
    db-schema-update: true

logging.level.org.activiti.engine.impl.persistence.entity: WARN
